name: Deploy ARC into Kubernetes
on:
  workflow_dispatch:

env:
  NAMESPACE: arc-systems
  VERSION: 1.0.6

jobs:
  Deploy-Cluster:
    runs-on: gha-runner-scale-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: ls
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install zip
    - run: echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kubeconfig.yaml

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - name: Install jq
      uses: dcarbone/install-jq-action@v2.1.0

    - run: 
        kubectl delete secret arc-version --namespace=$NAMESPACE --kubeconfig=kubeconfig.yaml || echo "secret does not exist"

    - run: kubectl create secret generic arc-version --namespace=$NAMESPACE --from-literal version=$VERSION --kubeconfig=kubeconfig.yaml

    - run: kubectl get secrets/arc-version --namespace=$NAMESPACE -o json --kubeconfig kubeconfig.yaml | jq -r .data.version | base64 --decode

    # - uses: cschleiden/replace-tokens@v1
    #   with:
    #     tokenPrefix: '${'
    #     tokenSuffix: '}'
    #     files: '["**/*.yaml"]'
    # - name: Helm tool installer
    #   uses: Azure/setup-helm@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
