name: Deploy ARC into Kubernetes
on:
  workflow_dispatch:

env:
  NAMESPACE: arc-systems

jobs:
  Deploy-Cluster:
    runs-on: gha-runner-scale-set
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: ls
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install zip
    - run: echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kubeconfig.yaml

    - run: sudo apt update -y
    - run: sudo apt upgrade -y
    - run: sudo apt install -y curl
    - run: sudo apt install -y jq

    - run:  curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - run:  chmod +x ./kubectl
    - run:  sudo mv ./kubectl /usr/local/bin/kubectl

    - run: echo VERSON=$(kubectl get secrets/arc-version --namespace=$NAMESPACE -o json --kubeconfig kubeconfig.yaml | jq -r .data.version | base64 --decode) >> $GITHUB_ENV

    - run: echo VERSONBUMP=$(echo $VERSON | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.) >> $GITHUB_ENV

    - run: kubectl delete secret arc-version --namespace=$NAMESPACE --kubeconfig=kubeconfig.yaml || echo "secret does not exist"

    - run: kubectl create secret generic arc-version --namespace=$NAMESPACE --from-literal version=$VERSONBUMP --kubeconfig=kubeconfig.yaml


    # - uses: cschleiden/replace-tokens@v1
    #   with:
    #     tokenPrefix: '${'
    #     tokenSuffix: '}'
    #     files: '["**/*.yaml"]'
    # - name: Helm tool installer
    #   uses: Azure/setup-helm@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
